// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetV1ConnectionListParams creates a new GetV1ConnectionListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1ConnectionListParams() *GetV1ConnectionListParams {
	return &GetV1ConnectionListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1ConnectionListParamsWithTimeout creates a new GetV1ConnectionListParams object
// with the ability to set a timeout on a request.
func NewGetV1ConnectionListParamsWithTimeout(timeout time.Duration) *GetV1ConnectionListParams {
	return &GetV1ConnectionListParams{
		timeout: timeout,
	}
}

// NewGetV1ConnectionListParamsWithContext creates a new GetV1ConnectionListParams object
// with the ability to set a context for a request.
func NewGetV1ConnectionListParamsWithContext(ctx context.Context) *GetV1ConnectionListParams {
	return &GetV1ConnectionListParams{
		Context: ctx,
	}
}

// NewGetV1ConnectionListParamsWithHTTPClient creates a new GetV1ConnectionListParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1ConnectionListParamsWithHTTPClient(client *http.Client) *GetV1ConnectionListParams {
	return &GetV1ConnectionListParams{
		HTTPClient: client,
	}
}

/* GetV1ConnectionListParams contains all the parameters to send to the API endpoint
   for the get v1 connection list operation.

   Typically these are written to a http.Request.
*/
type GetV1ConnectionListParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 connection list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1ConnectionListParams) WithDefaults() *GetV1ConnectionListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 connection list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1ConnectionListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 connection list params
func (o *GetV1ConnectionListParams) WithTimeout(timeout time.Duration) *GetV1ConnectionListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 connection list params
func (o *GetV1ConnectionListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 connection list params
func (o *GetV1ConnectionListParams) WithContext(ctx context.Context) *GetV1ConnectionListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 connection list params
func (o *GetV1ConnectionListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 connection list params
func (o *GetV1ConnectionListParams) WithHTTPClient(client *http.Client) *GetV1ConnectionListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 connection list params
func (o *GetV1ConnectionListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1ConnectionListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
