// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostV1AuthUserCreateReader is a Reader for the PostV1AuthUserCreate structure.
type PostV1AuthUserCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostV1AuthUserCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostV1AuthUserCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostV1AuthUserCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostV1AuthUserCreateUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostV1AuthUserCreateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /v1/auth/user/create] PostV1AuthUserCreate", response, response.Code())
	}
}

// NewPostV1AuthUserCreateOK creates a PostV1AuthUserCreateOK with default headers values
func NewPostV1AuthUserCreateOK() *PostV1AuthUserCreateOK {
	return &PostV1AuthUserCreateOK{}
}

/*
PostV1AuthUserCreateOK describes a response with status code 200, with default header values.

success.
*/
type PostV1AuthUserCreateOK struct {
}

// IsSuccess returns true when this post v1 auth user create o k response has a 2xx status code
func (o *PostV1AuthUserCreateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post v1 auth user create o k response has a 3xx status code
func (o *PostV1AuthUserCreateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post v1 auth user create o k response has a 4xx status code
func (o *PostV1AuthUserCreateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post v1 auth user create o k response has a 5xx status code
func (o *PostV1AuthUserCreateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post v1 auth user create o k response a status code equal to that given
func (o *PostV1AuthUserCreateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post v1 auth user create o k response
func (o *PostV1AuthUserCreateOK) Code() int {
	return 200
}

func (o *PostV1AuthUserCreateOK) Error() string {
	return fmt.Sprintf("[POST /v1/auth/user/create][%d] postV1AuthUserCreateOK ", 200)
}

func (o *PostV1AuthUserCreateOK) String() string {
	return fmt.Sprintf("[POST /v1/auth/user/create][%d] postV1AuthUserCreateOK ", 200)
}

func (o *PostV1AuthUserCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostV1AuthUserCreateBadRequest creates a PostV1AuthUserCreateBadRequest with default headers values
func NewPostV1AuthUserCreateBadRequest() *PostV1AuthUserCreateBadRequest {
	return &PostV1AuthUserCreateBadRequest{}
}

/*
PostV1AuthUserCreateBadRequest describes a response with status code 400, with default header values.

illegal request.
*/
type PostV1AuthUserCreateBadRequest struct {
	Payload string
}

// IsSuccess returns true when this post v1 auth user create bad request response has a 2xx status code
func (o *PostV1AuthUserCreateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post v1 auth user create bad request response has a 3xx status code
func (o *PostV1AuthUserCreateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post v1 auth user create bad request response has a 4xx status code
func (o *PostV1AuthUserCreateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post v1 auth user create bad request response has a 5xx status code
func (o *PostV1AuthUserCreateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post v1 auth user create bad request response a status code equal to that given
func (o *PostV1AuthUserCreateBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post v1 auth user create bad request response
func (o *PostV1AuthUserCreateBadRequest) Code() int {
	return 400
}

func (o *PostV1AuthUserCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/auth/user/create][%d] postV1AuthUserCreateBadRequest  %+v", 400, o.Payload)
}

func (o *PostV1AuthUserCreateBadRequest) String() string {
	return fmt.Sprintf("[POST /v1/auth/user/create][%d] postV1AuthUserCreateBadRequest  %+v", 400, o.Payload)
}

func (o *PostV1AuthUserCreateBadRequest) GetPayload() string {
	return o.Payload
}

func (o *PostV1AuthUserCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostV1AuthUserCreateUnauthorized creates a PostV1AuthUserCreateUnauthorized with default headers values
func NewPostV1AuthUserCreateUnauthorized() *PostV1AuthUserCreateUnauthorized {
	return &PostV1AuthUserCreateUnauthorized{}
}

/*
PostV1AuthUserCreateUnauthorized describes a response with status code 401, with default header values.

only admin user can create new user
*/
type PostV1AuthUserCreateUnauthorized struct {
	Payload string
}

// IsSuccess returns true when this post v1 auth user create unauthorized response has a 2xx status code
func (o *PostV1AuthUserCreateUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post v1 auth user create unauthorized response has a 3xx status code
func (o *PostV1AuthUserCreateUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post v1 auth user create unauthorized response has a 4xx status code
func (o *PostV1AuthUserCreateUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post v1 auth user create unauthorized response has a 5xx status code
func (o *PostV1AuthUserCreateUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post v1 auth user create unauthorized response a status code equal to that given
func (o *PostV1AuthUserCreateUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post v1 auth user create unauthorized response
func (o *PostV1AuthUserCreateUnauthorized) Code() int {
	return 401
}

func (o *PostV1AuthUserCreateUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v1/auth/user/create][%d] postV1AuthUserCreateUnauthorized  %+v", 401, o.Payload)
}

func (o *PostV1AuthUserCreateUnauthorized) String() string {
	return fmt.Sprintf("[POST /v1/auth/user/create][%d] postV1AuthUserCreateUnauthorized  %+v", 401, o.Payload)
}

func (o *PostV1AuthUserCreateUnauthorized) GetPayload() string {
	return o.Payload
}

func (o *PostV1AuthUserCreateUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostV1AuthUserCreateInternalServerError creates a PostV1AuthUserCreateInternalServerError with default headers values
func NewPostV1AuthUserCreateInternalServerError() *PostV1AuthUserCreateInternalServerError {
	return &PostV1AuthUserCreateInternalServerError{}
}

/*
PostV1AuthUserCreateInternalServerError describes a response with status code 500, with default header values.

Error.
*/
type PostV1AuthUserCreateInternalServerError struct {
	Payload string
}

// IsSuccess returns true when this post v1 auth user create internal server error response has a 2xx status code
func (o *PostV1AuthUserCreateInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post v1 auth user create internal server error response has a 3xx status code
func (o *PostV1AuthUserCreateInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post v1 auth user create internal server error response has a 4xx status code
func (o *PostV1AuthUserCreateInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post v1 auth user create internal server error response has a 5xx status code
func (o *PostV1AuthUserCreateInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post v1 auth user create internal server error response a status code equal to that given
func (o *PostV1AuthUserCreateInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post v1 auth user create internal server error response
func (o *PostV1AuthUserCreateInternalServerError) Code() int {
	return 500
}

func (o *PostV1AuthUserCreateInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/auth/user/create][%d] postV1AuthUserCreateInternalServerError  %+v", 500, o.Payload)
}

func (o *PostV1AuthUserCreateInternalServerError) String() string {
	return fmt.Sprintf("[POST /v1/auth/user/create][%d] postV1AuthUserCreateInternalServerError  %+v", 500, o.Payload)
}

func (o *PostV1AuthUserCreateInternalServerError) GetPayload() string {
	return o.Payload
}

func (o *PostV1AuthUserCreateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
